server:
  port: 8085
  name: Ms Funcionario

spring:
  application:
    name: ms-Funcionario
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/employee?retryWrites=true&w=majority
  rabbitmq:
    host: localhost
    port: 15672
    username: admin
    password: admin
    virtual-host: local-vh
  main:
    allow-bean-definition-overriding: true

#springdoc:
#  swagger-ui:
#    path: /employee-api-docs.html
#  paths-to-match: /**/employee/**

eldorado:
  jwt:
    secret: KaPdRgUkXp2s5v8y/B?E(H+MbQeThVmYq3t6w9z$C&F)J@NcRfUjXnZr4u7x!A%D
    expirationMs: 300000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka